name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Run Cypress tests (correct folder path)
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/intigration/examples/**/*.js   # ✅ Correct path to your spec files
          browser: chrome

      # 5️⃣ Upload screenshots (for debugging)
      - name: Upload Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # 6️⃣ Upload videos (for debugging)
      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
